openapi: 3.2.0
info:
  title: Simple Edge Discovery API
  version: 1.0.0
  x-camara-commonalities: 0.4.0
  description: '# Find the closest Edge Cloud Zone

    ---

    # Summary


    The Simple Edge Discovery API returns the name of the closest operator Edge

    Cloud Zone to a particular user device.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: '{apiRoot}/simple-edge-discovery/v1'
  variables:
    apiRoot:
      default: https://localhost:9091
      description: 'API root, defined by the service provider, e.g.

        `api.example.com` or `api.example.com/somepath`

        '
tags:
- name: Discovery
  description: Find the closest Edge Cloud Zone to the user device.
paths:
  /edge-cloud-zones:
    get:
      security:
      - openId:
        - simple-edge-discovery:edge-cloud-zones:read
      operationId: readClosestEdgeCloudZone
      parameters:
      - name: filter
        in: query
        required: true
        description: 'Filter the Edge Cloud Zones according to the parameter value.

          For this API the only supported value is `closest`.

          '
        schema:
          type: string
          enum:
          - closest
      - name: IPv4-Address
        in: header
        required: false
        description: The public IPv4 address allocated to the device by the network operator.
        example: 84.125.93.10
        schema:
          $ref: '#/components/schemas/SingleIpv4Addr'
      - name: Public-port
        in: header
        required: false
        description: The public TCP or UDP port allocated to the device by the network operator.
        example: 123
        schema:
          $ref: '#/components/schemas/Port'
      - name: IPv6-Address
        in: header
        required: false
        description: The public IPv6 address allocated to the device by the network operator.
        example: 2001:db8:85a3:8d3:1319:8a2e:370:7348
        schema:
          $ref: '#/components/schemas/DeviceIpv6Address'
      - name: Network-Access-Identifier
        in: header
        required: false
        description: '3GPP network access identifier for the subscription

          being used by the device.

          '
        schema:
          $ref: '#/components/schemas/NetworkAccessIdentifier'
      - name: Phone-Number
        in: header
        example: '+441234567890'
        required: false
        description: 'MSISDN in E.164 format (starting with country code) of

          the mobile subscription being used by the device. Optionally

          prefixed with ''+''.

          '
        schema:
          $ref: '#/components/schemas/PhoneNumber'
      - name: x-correlator
        in: header
        required: false
        description: "When the API Consumer includes the \"x-correlator\" header in the\nrequest, the API provider must include it in the response with\nthe same value that was used in the request. Otherwise, it is\noptional to include the \"x-correlator\" header in the response with\n any valid value. Recommendation is to use UUID for values.\n"
        schema:
          type: string
      responses:
        '200':
          description: 'Successful response, returning the closest Edge Cloud

            Zone to the user device identified in the request header.

            '
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeCloudZones'
        '400':
          description: 'Client eror - the required querystring was not provided

            '
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              examples:
                InvalidQuerystring:
                  summary: Invalid querystring
                  description: The 'filter' querystring parameter is missing or does not have a value of 'closest'
                  value:
                    status: 400
                    code: INVALID_QUERYSTRING
                    message: 'Querystring must be provided: filter=closest'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
        '406':
          $ref: '#/components/responses/Generic406'
        '422':
          $ref: '#/components/responses/Generic422'
        '429':
          $ref: '#/components/responses/Generic429'
        '500':
          $ref: '#/components/responses/Generic500'
        '501':
          $ref: '#/components/responses/Generic501'
        '502':
          $ref: '#/components/responses/Generic502'
        '503':
          $ref: '#/components/responses/Generic503'
        '504':
          $ref: '#/components/responses/Generic504'
      tags:
      - Discovery
      summary: Returns the name of the Edge Cloud Zone closest to user device identified in…
      description: 'On receiving this request, the network will return the name

        of the Edge Cloud Zone with the shortest network path to the end user

        device identified in the request.'
components:
  responses:
    Generic422:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_422_DEVICE_IDENTIFIERS_MISMATCH:
              description: Inconsistency between device identifiers not pointing to the same device
              value:
                status: 422
                code: DEVICE_IDENTIFIERS_MISMATCH
                message: Provided device identifiers are not consistent.
            GENERIC_422_DEVICE_NOT_APPLICABLE:
              description: Service is not available for the provided device
              value:
                status: 422
                code: DEVICE_NOT_APPLICABLE
                message: The Service is not available for the provided device.
            GENERIC_422_UNIDENTIFIABLE_DEVICE:
              description: The device identifier is not included in the request and the device information cannot be derived from the 3-legged access token
              value:
                status: 422
                code: UNIDENTIFIABLE_DEVICE
                message: The device cannot be identified.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic502:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_502_BAD_GATEWAY:
              description: Internal routing problem in the Server side that blocks to manage the service properly
              value:
                status: 502
                code: BAD_GATEWAY
                message: An upstream internal service cannot be reached.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_500_INTERNAL:
              description: Problem in Server side. Regular Server Exception
              value:
                status: 500
                code: INTERNAL
                message: Unknown server error. Typically a server bug.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Either out of resource quota or reaching rate limiting.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: API Server request limit is overpassed
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Either out of resource quota or reaching rate limiting.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic503:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_503_UNAVAILABLE:
              description: Service is not available. Temporary situation usually related to maintenance process in the server side
              value:
                status: 503
                code: UNAVAILABLE
                message: Service Unavailable.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            'GENERIC_403_INVALID_TOKEN_CONTEXT:':
              description: Reflect some inconsistency between information in some field of the API and the related OAuth2 Token
              value:
                status: 403
                code: INVALID_TOKEN_CONTEXT
                message: '{{field}} is not consistent with access token.'
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials.
            GENERIC_401_AUTHENTICATION_REQUIRED:
              description: New authentication is needed, authentication is no longer valid
              value:
                status: 401
                code: AUTHENTICATION_REQUIRED
                message: New authentication is required.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic406:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_406_NOT_ACCEPTABLE:
              description: 'API Server does not accept the media type (`Accept-*` header) indicated by API client

                '
              value:
                status: 406
                code: NOT_ACCEPTABLE
                message: 'The server cannot produce a response matching the content requested by the client

                  through `Accept-*` headers.

                  '
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic501:
      description: Not Implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_501_NOT_IMPLEMENTED:
              description: Service not implemented. The use of this code should be avoided as far as possible to get the objective to reach aligned implementations
              value:
                status: 501
                code: NOT_IMPLEMENTED
                message: This functionality is not implemented yet.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic504:
      description: Gateway Timeout
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_504_TIMEOUT:
              description: API Server Timeout
              value:
                status: 504
                code: TIMEOUT
                message: Request timeout exceeded.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
    Generic404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.
            GENERIC_404_DEVICE_NOT_FOUND:
              description: Device identifier not found
              value:
                status: 404
                code: DEVICE_NOT_FOUND
                message: Device identifier not found.
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
  schemas:
    ErrorInfo:
      type: object
      description: Error information
      required:
      - message
      - status
      - code
      properties:
        message:
          type: string
          description: A human readable description of what the event represents
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Friendly Code to describe the error
    DeviceIpv6Address:
      description: The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g.adding ::0 to the /64 prefix).
      type: string
      format: ipv6
      example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
    PhoneNumber:
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
      type: string
      pattern: ^\+[1-9][0-9]{4,14}$
      example: '+123456789'
    EdgeCloudZone:
      type: object
      description: 'An Edge Cloud Zone, uniquely identified by a combination

        of the value of the Edge Resource Name object and the value of the

        Provider object (the name of the cloud provider or operator hosting that

        edge cloud zone).

        '
      properties:
        edgeCloudZoneId:
          $ref: '#/components/schemas/EdgeCloudZoneId'
        edgeCloudZoneName:
          $ref: '#/components/schemas/EdgeCloudZoneName'
        edgeCloudProvider:
          $ref: '#/components/schemas/EdgeCloudProvider'
    EdgeCloudProvider:
      description: 'The company name of the Edge Cloud Zone provider.

        '
      type: string
    EdgeCloudZones:
      type: array
      items:
        $ref: '#/components/schemas/EdgeCloudZone'
      minItems: 1
      description: 'A collection of Edge Cloud Zones. For this Simple Edge

        Discovery API the collection will have at most one member (the closest

        Edge Cloud Zone to the user device indicated in the request).

        '
      additionalProperties: false
    NetworkAccessIdentifier:
      description: A public identifier addressing a subscription in a mobile network. In 3GPP terminology, it corresponds to the GPSI formatted with the External Identifier ({Local Identifier}@{Domain Identifier}). Unlike the telephone number, the network access identifier is not subjected to portability ruling in force, and is individually managed by each operator.
      type: string
      example: 123456789@domain.com
    Port:
      description: TCP or UDP port number
      type: integer
      minimum: 0
      maximum: 65535
    EdgeCloudZoneName:
      description: 'Edge Cloud Zone Name - the common name for the Edge Cloud Zone.

        '
      type: string
      additionalProperties: false
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: 84.125.93.10
    EdgeCloudZoneId:
      description: 'Operator-issued UUID for the Edge Cloud Zone.

        '
      type: string
      format: uuid
      additionalProperties: false
  headers:
    x-correlator:
      description: "When the API Consumer includes the \"x-correlator\" header in the request,\n the API provider must include it in the response with the same value t\n hat was used in the request. Otherwise, it is optional to include the\n \"x-correlator\" header in the response with any valid value.\n Recommendation is to use UUID for values.\n"
      required: false
      schema:
        type: string
  securitySchemes:
    openId:
      description: OpenID Provider Configuration Information.
      type: openIdConnect
      openIdConnectUrl: .well-known/openid-configuration
externalDocs:
  description: Product documentation at CAMARA.
  url: https://github.com/camaraproject/EdgeCloud
